version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /.github/workflows
    schedule:
      interval: weekly

# Dependabot does not support uv:
# https://docs.astral.sh/uv/guides/integration/dependency-bots/#dependabot
#  - package-ecosystem: pip
#    directory: /
#    schedule:
#      interval: daily
