repos:
  - repo: local
    hooks:
      - id: debug-1
        name: print xil source and version
        language: system
        verbose: true
        always_run: true
        pass_filenames: false
        entry: uv run python -c "import xil; print(xil.__path__, xil.__version__)"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
      - id: debug
        name: print xil source and version
        language: system
        verbose: true
        always_run: true
        pass_filenames: false
        entry: uv run python -c "import xil; print(xil.__path__, xil.__version__)"
