name: Release

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The index repository to publish to - PyPI or Test PyPI
        required: true
        default: pypi
        type: choice
        options:
          - pypi
          - test-pypi

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install --pip-args="-c .github/workflows/poetry-constraint.txt" poetry
      - name: Configure test PyPI repository
        if: inputs.repository == 'test-pypi'
        run: poetry config repositories.test-pypi https://test.pypi.org/legacy/
      - name: Build and publish the package
        run: poetry publish --build --repository ${{ inputs.repository }}
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          POETRY_PYPI_TOKEN_TEST_PYPI: ${{ secrets.TEST_PYPI_TOKEN }}
