name: Release

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The index repository to publish to - PyPI or Test PyPI
        required: true
        default: testpypi
        type: choice
        options:
          - pypi
          - testpypi

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PYPI_PUBLISH: true
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get uv version
        id: uv-version
        run: |
          content=$(cat .github/workflows/uv-constraint.txt)
          echo "version=${content#uv==}" >> $GITHUB_OUTPUT
      - uses: astral-sh/setup-uv@v4
        with:
          version: ${{ steps.uv-version.outputs.version }}
      - name: Build the package
        run: uv build --no-sources
      - name: Publish the package
        env:
          UV_PUBLISH_TOKEN: ${{ inputs.repository == 'pypi' && secrets.PYPI_TOKEN || secrets.TEST_PYPI_TOKEN }}
          UV_PUBLISH_URL: ${{ inputs.repository == 'pypi' && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
        run: uv publish
      - name: Upload source and wheel distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-build-archives
          path: dist/
