name: Tests

on:
  push:
    paths:
      - "**.py"
      - pyproject.toml
      - uv.lock
      - .github/workflows/uv-constraint.txt
      - .github/workflows/tests.yml
    branches:
      - main
      - "releases/**"
  pull_request:
    paths:
      - "**.py"
      - pyproject.toml
      - uv.lock
      - .github/workflows/uv-constraint.txt
      - .github/workflows/tests.yml
    branches:
      - main
      - "releases/**"
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"  # Daily at 6pm Israel standard time

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: pipx install --pip-args="-c ${{ github.workspace }}/.github/workflows/uv-constraint.txt" uv
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: uv.lock
      - name: Install dependencies
        run: uv sync
      - name: Run live tests (needing an internet connection)
        run: uv run coverage run -m pytest -m live
      - name: Run offline tests
        if: github.event_name != 'schedule'
        run: uv run coverage run -am pytest -m "not live" --disable-network
      - name: Report coverage
        if: github.event_name != 'schedule'
        run: uv run coverage report
      # The following step will be removed when all the project is covered with tests
      - name: Maintain 100% coverage on tested modules
        if: github.event_name != 'schedule'
        run: |
          uv run coverage report --fail-under 100 \
          xil/_currencies.py \
          xil/_headers.py \
          xil/_df_normalizer.py \
          xil/onezero.py \
          xil/discount.py \
          xil/mercantile.py \
          xil/leumi.py \
#          xil/poalim.py \
